### ISSUE TITLE
Kraken nethunter kernel for j7nxt   (SM-J701F)

### ISSUE THREAD

**Issue by RahulSharma716773** [Thiviyan/KRAKEN_7870_Nethunter#3]
Hlo Thiviyan, please help me i was searching nethunter kernel for my j7 nxt.
I have all repo install and download all toolchain and your kraken nethunter and followed all the instruction given by you.
edited makefile and bashrc file. but when i give command (make) for making for j7velte then i get this error. hope u understand my problem. please can u make nethunter kernel for my j701f. and update in release please or personal messege in my google account. Both image file and nethunter zip for j701f. i will very helpful if u do this thank u.
my google acc: trekfred88@gmail.com 
Error:

Starting J701X kernel build...
 Building OneUI variant 
----------------------------------------------
 
Building defconfig for J701X-ONEUI
 
 
 Cleaning build dir
make: ccache: Command not found
./scripts/gcc-version.sh: line 25: ccache: command not found
./scripts/gcc-version.sh: line 26: ccache: command not found
make: ccache: Command not found
drivers/net/wireless/Makefile:65: android version 1: 90000
drivers/net/wireless/Makefile:66: MAJOR_VERSION version 1: 9
drivers/net/wireless/qcacld-2.0/Kbuild:299: drivers/net/wireless/qcacld-2.0
security/samsung/defex_lsm/Makefile:60: [DEFEX] VTS false 
make: ccache: Command not found
./scripts/gcc-version.sh: line 25: ccache: command not found
./scripts/gcc-version.sh: line 26: ccache: command not found
make: ccache: Command not found
drivers/net/wireless/Makefile:65: android version 1: 90000
drivers/net/wireless/Makefile:66: MAJOR_VERSION version 1: 9
drivers/net/wireless/qcacld-2.0/Kbuild:299: drivers/net/wireless/qcacld-2.0
security/samsung/defex_lsm/Makefile:60: [DEFEX] VTS false 
 cleanup old configs 
 Copy j7veltesea_defconfig 
 No split config support! 
 Copy oneui_defconfig 
 Copy KRAKEN_defconfig 
 Set J701X-ONEUI to generated config 
----------------------------------------------
 
Building zImage for J701X-ONEUI
Make tmp_defconfig
make: ccache: Command not found
./scripts/gcc-version.sh: line 25: ccache: command not found
./scripts/gcc-version.sh: line 26: ccache: command not found
  HOSTCC  scripts/basic/fixdep
/bin/sh: 1: ccache: not found
scripts/Makefile.host:91: recipe for target 'scripts/basic/fixdep' failed
make[1]: *** [scripts/basic/fixdep] Error 127
Makefile:446: recipe for target 'scripts_basic' failed
make: *** [scripts_basic] Error 2
make: ccache: Command not found
./scripts/gcc-version.sh: line 25: ccache: command not found
./scripts/gcc-version.sh: line 26: ccache: command not found
make: ccache: Command not found
make[1]: ccache: Command not found
./scripts/gcc-version.sh: line 25: ccache: command not found
./scripts/gcc-version.sh: line 26: ccache: command not found
  HOSTCC  scripts/basic/fixdep
/bin/sh: 1: ccache: not found

. please make nethunter for my j701f j7 nxt in your computer. thank u.
or if can u help then solve.

**Comment by ghost** [comment]
apt install ccache

Try that bro
