### ISSUE TITLE
QUESTION: Does this kernel support RTL8192EU?

### ISSUE THREAD

**Issue by Dozairu** [Thiviyan/KRAKEN_7870_Nethunter#4]
As the title says, does this kernel have support for  RTL8192EU USB WI-FI? Also, do you plan on creating a simple-kernel/h-kernel variant for h-vendor users?

**Comment by Thiviyan** [comment]
i have used Simple Kernel base in KekHunterOS for J730x.. i can make a release of the kernel if you need it.

**Comment by Dozairu** [comment]
alright then, ty. I'll be looking forward to a simple kernel release. I use a J710X btw
